<?php

/*
|--------------------------------------------------------------------------
| Laravel FFMpeg Configuration
|--------------------------------------------------------------------------
|
| IMPORTANT: This configuration is ACTIVELY USED and must NOT be removed.
|
| Purpose: FFMpeg handles server-side audio conversion for stems and tempo
| variations generated by the audio analysis microservice.
|
| Usage Flow:
| 1. Audio microservice generates stems/tempo variations as WAV files
| 2. AudioAnalysisCallbackController receives webhook notification
| 3. ConvertAndPublishAudio job dispatches
| 4. AudioConversionService uses FFMpeg to convert WAV → OGG Opus
| 5. Converted files stored in R2/local storage for browser streaming
|
| Note: Main uploads use client-side MediaBunny processing (Phase 4),
| but microservice-generated audio still requires server-side FFMpeg.
|
| Package: pbmedia/laravel-ffmpeg
| Docs: https://github.com/protonemedia/laravel-ffmpeg
|
*/

return [
    /*
    |--------------------------------------------------------------------------
    | FFMpeg Binary Configuration
    |--------------------------------------------------------------------------
    |
    | Path to FFMpeg binary. On most systems, 'ffmpeg' is in PATH.
    | For custom installations, specify absolute path:
    | Example: '/usr/local/bin/ffmpeg' or '/opt/homebrew/bin/ffmpeg'
    |
    */
    'ffmpeg' => [
        'binaries' => env('FFMPEG_BINARIES', 'ffmpeg'),

        // Number of threads for encoding (12 = fast encoding on modern CPUs)
        // Set to false to disable multithreading (slower but lower CPU usage)
        'threads' => 12,
    ],

    /*
    |--------------------------------------------------------------------------
    | FFProbe Binary Configuration
    |--------------------------------------------------------------------------
    |
    | Path to FFProbe binary (ships with FFMpeg). Used for analyzing audio
    | file properties like duration, bitrate, codec, etc.
    |
    */
    'ffprobe' => [
        'binaries' => env('FFPROBE_BINARIES', 'ffprobe'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Processing Timeout
    |--------------------------------------------------------------------------
    |
    | Maximum time (seconds) for audio conversion operations.
    | 3600 seconds = 1 hour (sufficient for large stems/tempo files)
    |
    */
    'timeout' => 3600,

    /*
    |--------------------------------------------------------------------------
    | Logging Configuration
    |--------------------------------------------------------------------------
    |
    | Log channel for FFMpeg operations (encoding progress, errors, etc.)
    | Set to false to disable FFMpeg logging entirely.
    |
    */
    'log_channel' => env('LOG_CHANNEL', 'stack'),

    /*
    |--------------------------------------------------------------------------
    | Temporary Files Configuration
    |--------------------------------------------------------------------------
    |
    | Directory for temporary files during encoding operations.
    | Default: System temp directory (usually /tmp on Unix, %TEMP% on Windows)
    |
    */
    'temporary_files_root' => env('FFMPEG_TEMPORARY_FILES_ROOT', sys_get_temp_dir()),

    /*
    |--------------------------------------------------------------------------
    | Encrypted HLS Temporary Files
    |--------------------------------------------------------------------------
    |
    | Directory for temporary HLS (HTTP Live Streaming) encrypted segments.
    | Not currently used in Beat Forge but available for future features.
    |
    */
    'temporary_files_encrypted_hls' => env('FFMPEG_TEMPORARY_ENCRYPTED_HLS', env('FFMPEG_TEMPORARY_FILES_ROOT', sys_get_temp_dir())),
];
